### ISSUE TITLE
support CHUNK_GET for CERTIFICATE

### ISSUE THREAD

**Issue by hiption** [DMTF/libspdm#1018]
According to 10.8 GET_CERTIFICATE, the Responder shall fragment and serve CERTIFICATE message in chunks.

https://github.com/DMTF/libspdm/blob/e8c3632e1edcc9588714e84cb154705e8c908e97/library/spdm_responder_lib/libspdm_rsp_certificate.c#L114-L123

Current implementation does not support chunks.

**Comment by steven-bellock** [comment]
Yeah we had `CERTIFICATES` as a TODO since it already supported the equivalent of chunking in 1.0 and 1.1. We will work on this in the next few weeks / months.

**Comment by steven-bellock** [comment]
Interestingly, according to the specification, if both the Requester and the Responder support chunking, and the Requester only wants, say, the first 100 bytes of the certificate, it still needs to use the chunking mechanism, which seems inefficient.

**Comment by steven-bellock** [comment]
The problem in the specification is
>Endpoints that support the large SPDM message transfer mechanism message set, shall use the large SPDM
message transfer mechanism messages to manage the transfer of the requested certificate chain. Specifically:
>- The Requester shall set Offset to 0 and Length to 0xFFFF in the GET_CERTIFICATE request.

This assumes that the Requester always wants the entire certificate chain rather than, for example, just the root certificate. I have already filed a similar issue against the specification and I can just broaden its scope.

**Comment by jyao1** [comment]
What we need to do in this issue?

**Comment by jyao1** [comment]
@steven-bellock will check what is needed in this issue.

**Comment by steven-bellock** [comment]
#1205 has what I believe to be the solution but it'll need some more unit tests before it can be merged.
