### ISSUE TITLE
API : libspdm_get_response_algorithms

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#1163]
Hello,
File name : libspdm_rsp_algorithms.c
API: libspdm_get_response_algorithms
Line: Around 408

Code snippet:
```
for (index = 0; index < spdm_request->header.param1; index++) {
            switch (struct_table->alg_type) {
            case SPDM_NEGOTIATE_ALGORITHMS_STRUCT_TABLE_ALG_TYPE_DHE:
                spdm_context->connection_info.algorithm
                .dhe_named_group =
                    struct_table->alg_supported;
```                    
Shouldn't this logic be like the below for the switch statement:
`switch (struct_table[index]->alg_type)`

**Comment by steven-bellock** [comment]
What `struct_table` points to gets updated at line 437. Note that, due to the existence of the external algorithms, the size of the `struct_table` can vary. Since libspdm doesn't support external algorithms the Responder will never set `ExtAlgCount` to `1` and so that could be optimized / refactored out, maybe to use array indices in the for-loop.

**Comment by jyao1** [comment]
I don't think it is a good idea to use struct_table\[index\], what is not reliable.
Even it is right today, it may be changed in the future.

Using pointer with address addition can guarantee the result is always right.
