### ISSUE TITLE
Buffer Management Refactor?

### ISSUE THREAD

**Issue by richkong88** [DMTF/libspdm#1213]
With the addition of chunking, the buffer management has gotten quite complex. Currently, there are many buffers with different names:
sender buffer, receiver buffer, scratch space (currently divided into three buffers), and the last_spdm_request.  After being away for a few months, I find it difficult to follow and somewhat error prone.  I'm wondering if we should look into a refactoring of all of this to make it more manageable and easier to understand?

**Comment by jyao1** [comment]
Here is my thought: The buffer usage is below:
1) Sender Buffer: The buffer is to send the a message in transport layer from local. This is defined for optimization, because the device may allocate DMA memory directly to avoid copy.

The "SenderBufferSize" might be bigger or smaller than remote SPDM `DataTransferSize`. However, "SenderMessageSize" shall be smaller than or equal to remote SPDM `DataTransferSize`.

2) Receiver Buffer: The buffer is to receive the a message in transport layer from remote/peer. This is defined for optimization, because the device may allocate DMA memory directly to avoid copy.

To follow SPDM spec, "ReceiverBufferSize" shall be bigger than or equal to local SPDM `DataTransferSize`.

3) Scratch Space: It is used for libspdm internal usage. There is no requirement for the device driver be aware it. The integrator can allocate any space (heap or global data) for it.

The last_spdm_request is to cache the last_spdm_request, as such the spdm responder can handle it later.
I think "last_spdm_request" should be part of scratch space. It is not there, just because we defined it before we introduce scratch space.

In the future, I think we need define "last_spdm_response" to support retry. - But we can hold it until we really want to add support.

For this issue, I suggest 
1) Merge "last_spdm_request" into "scratch buffer".
2) Document the three buffers' usage as above. (sender buffer, receiver buffer, scratch space)

**Comment by steven-bellock** [comment]
Concerning compile-time macros in general, if a macro isn't used to allocate space at compile-time, or if it doesn't confer optimizations, then it should probably be made run-time assignable.

**Comment by jyao1** [comment]
The design without chunking is documented at https://github.com/DMTF/libspdm/discussions/702.

We should document the chunking case.
requester/responder, session/non-session, large message send/receive

**Comment by jyao1** [comment]
9/19/2022 - Make it Q4 stable task.

**Comment by richkong88** [comment]
Sorry, I don't have time to work on this this quarter and probably not next. If someone else would like to try, please do. Or just close since it was just a suggestion for a refactor and not functionality.

**Comment by jyao1** [comment]
We already did buffer refactoring for libspdm 3.0. Close it.

@richkong88 , feel free to review and submit new issue, if you see more action is needed.
