### ISSUE TITLE
Checking the negotiated state in PSK_EXCHANGE

### ISSUE THREAD

**Issue by KwonHyunSoo** [DMTF/libspdm#1553]
Hi all,

The Spec. v1.2.1 says that "If the two endpoints support session key establishment with the PSK (Pre-Shared Key) option, then Negotiated State is not applicable and VCA is not stored." in _10.1.1 Negotiated state preamble_ and "During PSK provisioning, the capabilities of an endpoint and supported algorithms can be communicated to the peer. Therefore, SPDM commands GET_CAPABILITIES and NEGOTIATE_ALGORITHMS are not required during session key establishment with the PSK option, and Negotiated State shall not be supported." in _10.18 PSK_EXCHANGE request and PSK_EXCHANGE_RSP response messages_

However, it seems that PSK_EXCHANGE command in libspdm checks the negotiated state and produces the unexpected request error if it receives such request before conducting NEGOTIATE_ALGORITHMS command as follows:
https://github.com/DMTF/libspdm/blob/2885f78ba88e69ae13ebcedf4474738f87e1a4e3/library/spdm_responder_lib/libspdm_rsp_psk_exchange.c#L125-L129

Can I skip the checking of the negotiated state in PSK_EXCHANGE command?

**Comment by jyao1** [comment]
I think it is expected to have connection_state as LIBSPDM_CONNECTION_STATE_NEGOTIATED.

The expected behavior from integrator is: to provision capability and algorithm, then set the connection_state to LIBSPDM_CONNECTION_STATE_NEGOTIATED.

It is also required step to restore VCA cache.

For example, https://github.com/DMTF/spdm-emu/blob/main/spdm_emu/spdm_emu_common/nv_storage.c#L143-L147

**Comment by jyao1** [comment]
2023/1/2 - discussed in the meeting. Agree to keep the state.

**Comment by KwonHyunSoo** [comment]
Thanks!
