### ISSUE TITLE
Question on libspdm_check_request_flag_compability() with respect to cert_cap

### ISSUE THREAD

**Issue by mcsmonk** [DMTF/libspdm#1632]
issue #1603 is solved by #1616
``` C
        /* Checks that originate from certificate or public key capabilities. */
        if ((cert_cap == 1) || (pub_key_id_cap == 1)) {
            /* Certificate capabilities and public key capabilities cannot both be set. */
            if ((cert_cap == 1) && (pub_key_id_cap == 1)) {
                return false;
            }
            if ((chal_cap == 0) && (key_ex_cap == 0)) {
                return false;
            }
        } else {
            /* If certificates or public keys are not enabled then these capabilities
             * cannot be enabled. */
--         if ((chal_cap == 1) || (key_ex_cap == 1) || (mut_auth_cap == 1)) {
++       if ((chal_cap == 1) || (mut_auth_cap == 1)) {
                return false;
            }
        }
```

I wonder why only `key_ex_cap` is deleted in the check branch. I think that both `chal_cap` and `key_ex_cap` sholud be deleted if `key_ex_cap` might be deleted.

On the other hand, I think that check on whether `chal_cap` or `key_ex_cap` are not zero must be remained in case which `cert_cap` and `pub_key_id_cap` are all zero beacuse both `CHALLENGE_AUTH` and `KEY_EXCHANGE_RSP` response messages have signatures.

**Comment by jyao1** [comment]
This is because "key_ex_cap" does not requires mutual authentication.
But "chal_cap" and "mut_auth_cap" require mutual authentication.

**Comment by xiangfeima** [comment]
@jyao1 same question here, the change we made with 2.3.1 release, eventually, why the capabilities conbination `(CERT_CAP=0, PUB_KEY_ID_CAP=0, KEY_EX_CAP=1)` of Requester is legal? 

As I see if Requester `(KEY_EX_CAP = 1)`,  then either `(CERT_CAP=1)` or `(PUB_KEY_ID_CAP = 1)` must be set,
since Requester has to verify the signature in KEY_EXCHANGE_RSP from Responder.
The question so far doesn't have Mutual auth involved. 

Could you elaborate this further? Thanks.

**Comment by steven-bellock** [comment]
Note the text above `Flag fields definitions for the Requester`.
>Unless otherwise stated, if a Requester indicates support of a capability associated with an SPDM request or response message, it means the Requester can receive the corresponding request and produce a successful response. In other words, the Requester is acting as a Responder to that SPDM request associated with that capability. For example, if a Requester sets CERT_CAP bit to 1, the Requester can receive a GET_CERTIFICATE request and send back a successful CERTIFICATE response message.

Ultimately the Responder doesn't care about the Requester's `KEY_EX_CAP`. It could be removed from `GET_CAPABILITIES.Flags.KEY_EX_CAP`, save for the off chance the Responder might unload its `KEY_EXCHANGE_RSP` code and data if the Requester doesn't support `KEY_EXCHANGE`.

I do think the specification could be more clear about the `Unless otherwise stated` portion, so I'll file an issue against the specification for that.

**Comment by mcsmonk** [comment]
| flag | Description |
| --- | --- |
| `CERT_CAP` | If set, Requester supports `DIGESTS` and `CERTIFICATE` response messages. |
| `KEY_EX_CAP` | If set, Requester supports `KEY_EXCHANGE` messages. If set, `ENCRYPT_CAP` or `MAC_CAP` shall be set. |

I got confused because of some flags for literally capability and the other flags for meaning to support response message as a responder. But, I understand now.
