### ISSUE TITLE
Cryptography algorithm compatibility

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1635]
The configuration file says https://github.com/DMTF/libspdm/blob/af2afce708271b50bee57fff3c0cbd21a5f157a4/include/library/spdm_lib_config.h#L104-L106

Presumably, within NIST any of the algorithms can be mixed and matched. And presumably, within SMx any of the algorithms can be mixed and matched. The main requirement is that algorithms shouldn't be mixed and matched between NIST and SMx. However, given a Requester and Responder that both support NIST and SMx, it's up to the Responder, during its `ALGORITHMS` response, to decide between only NIST or only SMx algorithms. Note that libspdm skews towards NIST, as the libspdm priority tables have SMx at the bottom. 

Should libspdm enforce the division between NIST and SMx, or should we leave it up to the Integrator?

There should also be some wording in the specification or white paper recommending not to mix and match.

**Comment by steven-bellock** [comment]
@jyao1 and @xiaoyuruan

**Comment by xiaoyuruan** [comment]
If it's a general libspdm reference code, this should be decided by integrator and libspdm should not enforce.
If it's a FIPS SKU libspdm reference code, libspdm should enforce only NIST algorithms may be selected.

**Comment by jyao1** [comment]
> given a Requester and Responder that both support NIST and SMx, it's up to the Responder, during its ALGORITHMS response, to decide between only NIST or only SMx algorithms.

Agree. But currently, we dont have configuration say: NIST set or SMx set. All SMx are listed as last choice.

> If it's a FIPS SKU libspdm reference code, libspdm should enforce only NIST algorithms may be selected.
Yes. Currently, we have FIPS_MODE, and algorithms are enforced.


This sentence is there, because the algorithm in "FIPS 140" (NIST/FIPS) and algorithm in "GM/T 0028 Security requirements for cryptographic modules" (SMx) are different. We want to tell the integrator.
Now, since we have FIPS_MODE, I think it is good enough. I think:
1) In FIPS mode, libspdm does the enforcement.
2) In non-FIPS mode, libspdm leaves to the integrator.
3) We may consider GMT_0028 mode later. But we dont need worry about that now.

**Comment by jyao1** [comment]
1/16/2023 - Agreed. Close.
