### ISSUE TITLE
Setting ENCRYPT_CAP to 1 and MAC_CAP to 0 in GET_CAPABILITIES message leads to LIBSPDM_ASSERT

### ISSUE THREAD

**Issue by PavelPu123** [DMTF/libspdm#1986]
While setting the mentioned configuration in GET_CAPABILITIES message we're getting to:

https://github.com/DMTF/libspdm/blob/6684f43117784b12e25e665df65d1d122540f11f/library/spdm_common_lib/libspdm_com_context_data_session.c#L62

As I understand there should be a verification of this combination somewhere in:
https://github.com/DMTF/libspdm/blob/6684f43117784b12e25e665df65d1d122540f11f/library/spdm_responder_lib/libspdm_rsp_capabilities.c#L70-L85
and there should be an error message since this combination violates the spec.

Thanks.

**Comment by steven-bellock** [comment]
Encryption-only sessions are legal according to 0274, but not to 0277. Since libspdm requires 0277 I am fine putting the check in `GET_CAPABILITIES / CAPABILITIES`. However the Responder Validator also uses that logic, so I am not sure what would happen there. @jyao1 does the Responder Validator also assume the Responder implements 0277 if it supports secure sessions?

**Comment by jyao1** [comment]
I think we can assume DSP0277 at this moment.

Otherwise we dont know how to establish session and send session message.

**Comment by jyao1** [comment]
It seems we had better add such check in capability and reject this configuration earlier to avoid ASSERT.

**Comment by PavelPu123** [comment]
>what use case you want to support by setting ENCRYPT_CAP to 1 and MAC_CAP to 0 ?

We are testing the code for negative cases and that's one of them.
