### ISSUE TITLE
Enabling #define flags for optional messages

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#2]
Wondering the possibility for expanding the #define flags in SpdmLibConfig.h to include different optional messages and/or capabilities, such that the code for handling the response to these messages is #define'd out and not compiled.

The scenario I had in mind is for a memory-constrained Responder. For example, if CERT_CAP isn't going to be utilized, a user would be able to set some define, say "#OPENSPDM_RESPONDER_CERT_CAP_SUPPORT 0". This define would then remove the related certificate handling code, leaving only the necessary error handling code - that way, in case the Requester still sent GET_DIGESTS/GET_CERTIFICATE, the Responder would respond with expected error.

It would require some thinking through - likely requiring warning/error if user tries to set a capability that was compiled out. However, it would be a great way for a consumer of OpenSPDM, with code-size limitations and a static set of capabilities, to easily trim down the code size without having to manually remove messages.

It is for microcontroller case - memory constrain environment. Compiler-time optimization to save space.

**Comment by taprinz** [comment]
I can now look into this, will update when I have proposal implementation

**Comment by steven-bellock** [comment]
Can also extend this to the cryptography functions as well. If, for example, a responder does not support encryption then all the encryption functionality can be removed more easily.

**Comment by taprinz** [comment]
There's a lot that can be done here - creating #defines for certain capabilities also allows us to remove certain (often large) structures from the spdm_context_t struct as well, since they won't be used.

The tricky part would be balancing the ability to easily create a modular implementation of libspdm, alongside avoiding an intricate web of #ifdef and #ifndef macros littering the codebase. This may take some planning and investigation to determine what can be trimmed, especially cleanly.

**Comment by jyao1** [comment]
I think we can start with SPDM_VERSION 1.0, 1.1, or 1.2, 2.0 in the future.

**Comment by taprinz** [comment]
Providing a small update here. I have made a first attempt at this, but it ended up cluttering the codebase with #ifdef and #ifndef.
I'm going to try and clean up, post a proof-of-concept for feedback to see if this is something we think we can cleanly support.

**Comment by rkongintel** [comment]
Thanks for pointing me to the thread.  I tried this (#if #endif to eliminate GET_DIGEST, GET_CERTIFICATE, and CHALLENGE) and it does litter the source code, but mostly in the ULTs.  Personally, I feel the library changes aren't really that bad, but the #if/#endifs around the ULTs are a mess.  Changing it this way does give the compiler the ability to check that you didn't accidentally miss something.  If any one is interesting in seeing the code, let me know and I can push it to my public branch.

I also tried an alternative. Rather than ifdefing the code,  I tried just commenting out the request/response handlers I didn't want in my image: The code is in spdm_responder_lib/receive_send.c table: spdm_get_response_struct_t mSpdmGetResponseStruct[] = { };

The linker will then get rid of the associated functions I don't use/care about. I only did this for my experimental work as I imagine many ULTs would fail with this change. This is definitely less messy, but it doesn't have the compiler checking that you're not accidentally including something you may not really want.

**Comment by rkongintel** [comment]
You can take a look at my changes here: https://github.com/rkongintel/libspdm/pull/1
I'm new to the project, and still getting familiar with the code, so I didn't try to tackle trimming data sizes within the context. I can see how it can easily get out of hand.  

Looking at the changes now, I touched a lot of files. It looks more messy than I first thought, but many of the #if/#endif in the library are around whole files rather than parts of functions.

**Comment by jyao1** [comment]
I think it is good idea to add FLAG.

Some feedback:
1) I prefer to define it in include/library/spdm_lib_config.h instead of include/industry_standard/spdm.h.
2) I suggest we add capability check - if an entity includes disabled cap flag, the libspdm should ASSERT().
3) I feel we should use SPDM_DISABLE_*** instead of SPDM_ENABLE_***.

**Comment by rkongintel** [comment]
@jyao1 For #2, as an example for SPDM_DISABLE_CHALLENGE, do you mean in the spdm_set_data function, when receiving a SPDM_DATA_CAPABILITY_FLAGS parameter, ASSERT that the capability data does NOT have the (SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CHAL_CAP | SPDM_GET_CAPABILITIES_REQUEST_FLAGS_CHAL_CAP) set?

**Comment by rkongintel** [comment]
It seems like there are other non-capability related features a user would want to turn on/off based on a switch. (Currently defined as OPENSPDM_***_SUPPORT in spdm_lib_config.h). Maybe keep the switch as a separate name from caps for consistency, but the switch sets the capability to no on bits? And still use the switch for #if SWITCH/endif around the code?

**Comment by jyao1** [comment]
> @jyao1 For #2, as an example for SPDM_DISABLE_CHALLENGE, do you mean in the spdm_set_data function, when receiving a SPDM_DATA_CAPABILITY_FLAGS parameter, ASSERT that the capability data does NOT have the (SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CHAL_CAP | SPDM_GET_CAPABILITIES_REQUEST_FLAGS_CHAL_CAP) set?

That is correct.

**Comment by jyao1** [comment]
> Should we tie this directly to capabilities? And just have the defines be capabilities themselves?
> Then, we wouldn't have to worry about some user enabling a set of messages that is incompatible with the capabilities they have set. And it would automatically trim the code size for messages user expects to support.
> 
> It would limit the ability to change the list of supported capabilities at runtime, but do we ever expect to do that? We can remove them still, depending on the capabilities of requester and responder. But we would never really expect to add any, right?

Sorry, I hardly understand what the proposal is. Can you provide some example, or sample code?

**Comment by taprinz** [comment]
> Sorry, I hardly understand what the proposal is. Can you provide some example, or sample code?

I.e.

Rather than defining the macros to remove support for individual messages, like so:
```
#define SPDM_DISABLE_GET_DIGESTS         1
#define SPDM_DISABLE_GET_CERTIFICATES 1
#define SPDM_DISABLE_CHALLENGE           1
```
and adding the following capability checks, for each possible message and capability combination:

```
#ifdef SPDM_DISABLE_GET_DIGESTS
ASSERT(spdm_is_capabilities_flag_supported( spdm_context, FALSE, 0,
		    SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CERT_CAP))
#endif
#ifdef SPDM_DISABLE_GET_CERTIFICATE
ASSERT(spdm_is_capabilities_flag_supported( spdm_context, FALSE, 0,
		    SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CERT_CAP))
#endif
```

We instead base the macros to add/remove support for specific capabilities.
For example, the defines could be as so
`
#define SPDM_DISABLE_CAPABILITY_CERT_CAP 1
#define SPDM_DISABLE_CAPABILITY_KEY_EX_CAP 1
`

Then, it would be simpler, since we can add the asserts only when the user sets the capabilities:

```
spdm_set_data (...)
{
	case SPDM_DATA_CAPABILITY_FLAGS:
#ifdef SPDM_DISABLE_CAPABILITY_CERT_CAP
               ASSERT(data == SPDM_DATA_CAPABILITY_CERT)
#endif
#ifdef SPDM_DISABLE_CAPABILITY_KEY_EX_CAP
               ASSERT(data == SPDM_DATA_CAPABILITY_KEY_EX)
#endif
}
````

The idea here, being that it would minimize the coverage matrix of testing what combination of messages is allowed, and what is not.

**Comment by steven-bellock** [comment]
I prefer to have a base system that just supports the four required requests and then new capabilities are added at compile time with
`#define SPDM_ENABLE_CAPABILITY_CERT_CAP 1`

**Comment by taprinz** [comment]
@steven-bellock yeah, that's most preferable.
Then, the supported capabilities can just be determined by the compile time flags, rather than requiring the user to set the capabilities at runtime with spdm_set_data().

**Comment by rkongintel** [comment]
I like the idea of having a baseline of support for required requests/responses, then adding in the optional ones with the SPDM_ENABLE_***_CAP. I feel it would be easier for users to add in any extras they want, rather than removing what they don't need.  

If we are good with this method, I can get the changes started for a couple caps (CERT/CHALLENGE), and put it out for review.

**Comment by jyao1** [comment]
Agree

**Comment by rkongintel** [comment]
There seem to be multiple CAP bits for GET MEASUREMENTS related. 

#define SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_MEAS_CAP (BIT3 | BIT4)
#define SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_MEAS_CAP_NO_SIG BIT3
#define SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_MEAS_CAP_SIG BIT4
#define SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_MEAS_FRESH_CAP BIT5

Do you think a single compile switch (SPDM_ENABLE_GET_MEASUREMENTS_CAP) to control them all would be sufficient? And if users need finer grain of control, leave it up to them to make the change in their own versions of the code?

Same question for the PSK Cap.

#define SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_PSK_CAP (BIT10 | BIT11)
#define SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_PSK_CAP_RESPONDER BIT10
#define SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_PSK_CAP_RESPONDER_WITH_CONTEXT BIT11

**Comment by taprinz** [comment]
In my opinion, we should do whatever we can to avoid requiring end-users to make modifications to the libspdm internal workings. Any spec-defined options should be controlled via configuration file (spdm_lib_config.h) as long as it is not implementationally prohibitive to do so.

For the measurement CAP bits, it seems that we expect end user to select one of following options:
- No measurements
- Measurements with signature
- Measurements no signature

I think we should provide the user with the following flags: SPDM_ENABLE_MEASUREMENTS_CAP_WITH_SIG and SPDM_ENABLE_MEASUREMENTS_CAP_NO_SIG. Only one should be allowed. If neither selected, measurements are not enabled at all.

Then, the user should be able to optionally specify SPDM_ENABLE_GET_MEASUREMENTS_FRESH_CAP, but only if measurements has been enabled via the above two defines.

Internally, we can define a "SPDM_ENABLE_MEASUREMENTS_CAP" which OR's the defines of the above capabilities to determine whether measurements in general are enabled. Then, for specific measurement functionalities, we check the specific capability flags.

**Comment by jyao1** [comment]
I think we are talking building selection, not runtime selection, right?
I recommend we only have one flag - SPDM_ENABLE_GET_MEASUREMENTS_CAP.

Because a requester does not know what cap responder has at build, it only knows at runtime.

**Comment by taprinz** [comment]
True - I was thinking mostly with respect to responder case, we could set these flags at build time. But requester will not be able to determine until runtime.

**Comment by rkongintel** [comment]
Ok. So one "flag" to rule them all?

**Comment by jyao1** [comment]
> True - I was thinking mostly with respect to responder case, we could set these flags at build time. But requester will not be able to determine until runtime.

I see. That is also valid point.
Two flags solution will make code look complicated. But I am not sure how much size can be saved.

May I recommend to have a size impact evaluation further? With latest tree, it is quite easy to collect size info.

**Comment by jyao1** [comment]
Basically, if we can see a significant code size saving benefit, I think we can use two flags.
However, if the saving is trivial, I think one flag is enough.
We need make decision based upon real data.

**Comment by taprinz** [comment]
The more I think about it, I wonder whether we need to add flag for requester. There is no matching measurement capability that requester would specify. And there's not much code specific to measurements for requester - besides 'spdm_get_measurement', which can easily be compiled out if the code is never called by a given implementation. Otherwise, in CHALLENGE and KEY_EXCHANGE messages, there's a small amount of measurement code, but it can mostly be left untouched.

I think there is some utility for keeping list of capability flags matching defined capabilities in SPDM spec, rather than deviating. Since it guarantees flags would only trim out code at spec-defined boundaries, and is clear to user what impact is of enabling messages.

**Comment by rkongintel** [comment]
I've been looking through the code and I can't find anything that's worth adding separate compilation flags for MEASUREMENTS - SIG/NO_SIG/FRESH.  There maybe single if small if statements to wrap, that don't really add much savings, and complicate the code more. My feeling is to just have a single flag.  If you see large bodies of code that have potential for savings, please let me know.

**Comment by taprinz** [comment]
Yeah that makes sense. I guess my position of being a stickler here is the usage of the name "CAP". If we use that naming, it might get confusing to an end user if the list of capabilities, and advertised effects, is different than what is in the spec.

I can imagine that other capabilities aren't going to provide significant code savings, and probably won't be worth flags either. In this case, I think we'll just need to clearly document that these flags are for optimization, rather than enabling specific capabilities, and that these capabilities still need to be set with 'spdm_set_data'.

**Comment by rkongintel** [comment]
I put my changes [here ](https://github.com/DMTF/libspdm/pull/182) and tried to update the comments in spdm_lib_config.h to be more detailed with what we are doing.

**Comment by steven-bellock** [comment]
Voted to close at 6-Dec-2021 meeting.
