### ISSUE TITLE
Does the LIBSPDM library verify the non-leaf certificate basic_constraints CA == TRUE? 

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2017]

**Comment by Wenxing-hou** [comment]
No. The Libspdm only check the leaf cert basic_constraints in `libspdm_x509_certificate_check`.
But the non-leaf cert basic_constraints may not be needed to check.
Because all cert are verified by the trust CA cert.

https://github.com/DMTF/libspdm/blob/8248e6245f89704f789b0e81eb95bbfe19f0394e/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1305-L1320

**Comment by xiangfeima** [comment]
The intermediate certificate CA flag would be checked by the underlaying certificate parser (mbedtls and openssl is provided under os_stub dir, meanwhile I think we are open to integrator customized parser).

If you take a deep look into `libspdm_x509_verify_cert_chain` routine,
for openssl, it will finally go into 
https://github.com/openssl/openssl/blob/31157bc0b46e04227b8468d3e6915e4d0332777c/crypto/x509/x509_vfy.c#L451

and in the mbedtls case, it would finally go into
https://github.com/Mbed-TLS/mbedtls/blob/dd79db10014d85b26d11fe57218431f2e5ede6f2/library/x509_crt.c#L2597

So in general, I think it depends on the certificate parser. And IMHO it is not libspdm's responsibility to check everything in the certificate chain.

@Wenxing-hou @steven-bellock please correct me if I get the wrong idea.

**Comment by steven-bellock** [comment]
Yes, it depends on the certificate parser / verifier as well as the cryptography algorithm support. SPDM only specifies the possible algorithms (asymmetric and hash) for the leaf certificate, but the other certificates in the chain could use anything; for example SHA-1 hashes.
