### ISSUE TITLE
Responder's handling of `CHUNK_GET` is incomplete

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2141]
A Responder may return a `LargeResponse` error if the size of the response is larger than the `DataTransferSize` of the Requester or the transmit buffer size of the Responder. However libspdm ignores the case when the transmit buffer of the Responder is small.

https://github.com/DMTF/libspdm/blob/6674aa87c5a3b6991e25e22fcd1bf44e2a111331/library/spdm_responder_lib/libspdm_rsp_receive_send.c#L614-L620 checks if the response is larger than at least one of the two buffers. If it is then `LargeResponse` is eventually sent to the Requester. When the Responder receives `CHUNK_GET` it ignores its own transmit buffer. For example
https://github.com/DMTF/libspdm/blob/6674aa87c5a3b6991e25e22fcd1bf44e2a111331/library/spdm_responder_lib/libspdm_rsp_chunk_get.c#L116-L119 This leads to hitting assertions like https://github.com/DMTF/libspdm/blob/main/library/spdm_responder_lib/libspdm_rsp_chunk_get.c#L107 and https://github.com/DMTF/libspdm/blob/6674aa87c5a3b6991e25e22fcd1bf44e2a111331/library/spdm_responder_lib/libspdm_rsp_chunk_get.c#L122

This should be fixed in 2.3 as well. Note that I fixed this issue in the specification for `CHUNK_SEND` but not `CHUNK_GET` : https://github.com/DMTF/SPDM-WG/pull/2715.

**Comment by steven-bellock** [comment]
@jyao1 @Wenxing-hou I don't understand how `spdm-emu` passes the "test" where Responder and Requester have different buffer sizes.

**Comment by jyao1** [comment]
@Zhiqiang520 , please take a look.

**Comment by Zhiqiang520** [comment]
@jyao1 @steven-bellock @Wenxing-hou  
I found the root cause why the **current** [`spdm-emu`](https://github.com/DMTF/spdm-emu/commit/94668a9b76d39401b5c043552b7045ca505c87bc) passes the "test" where Responder and Requester have different buffer sizes.

the root cause is the **current** submodule [`libspdm`](https://github.com/DMTF/libspdm/tree/6684f43117784b12e25e665df65d1d122540f11f) in the **current** [`spdm-emu`](https://github.com/DMTF/spdm-emu/commit/94668a9b76d39401b5c043552b7045ca505c87bc) is **a little old**, it will not refer to the `context->local_context.capability.sender_data_transfer_size`.

1. the current `chunk_check.yml` defined the MACRO `LIBSPDM_SENDER_BUFFER_SIZE` and `LIBSPDM_RECEIVER_BUFFER_SIZE`.
https://github.com/DMTF/spdm-emu/blob/94668a9b76d39401b5c043552b7045ca505c87bc/.github/workflows/chunk_check.yml#L29
2. the value of above two MACRO `LIBSPDM_SENDER_BUFFER_SIZE` and `LIBSPDM_RECEIVER_BUFFER_SIZE` are used in `spdm_requester_emu/spdm_requester_spdm.c` and `spdm_responder_emu/spdm_responder_spdm.c`.
https://github.com/DMTF/spdm-emu/blob/94668a9b76d39401b5c043552b7045ca505c87bc/spdm_emu/spdm_requester_emu/spdm_requester_spdm.c#L197-L203
https://github.com/DMTF/spdm-emu/blob/94668a9b76d39401b5c043552b7045ca505c87bc/spdm_emu/spdm_responder_emu/spdm_responder_spdm.c#L159-L165
3. finally set into `context->local_context.capability.sender_data_transfer_size` and `context->local_context.capability.data_transfer_size` at the following line 1978 and 1984.
https://github.com/DMTF/libspdm/blob/6684f43117784b12e25e665df65d1d122540f11f/library/spdm_common_lib/libspdm_com_context_data.c#L1974-L1984
4. But due to the **current** submodule [`libspdm`](https://github.com/DMTF/libspdm/tree/6684f43117784b12e25e665df65d1d122540f11f) in the **current** [`spdm-emu`](https://github.com/DMTF/spdm-emu/commit/94668a9b76d39401b5c043552b7045ca505c87bc) is **a little old**, it will not refer to the `context->local_context.capability.sender_data_transfer_size`, so the **current** [`spdm-emu`](https://github.com/DMTF/spdm-emu/commit/94668a9b76d39401b5c043552b7045ca505c87bc) passes the "test" where Responder and Requester have different buffer sizes.
https://github.com/DMTF/libspdm/blob/6684f43117784b12e25e665df65d1d122540f11f/library/spdm_responder_lib/libspdm_rsp_receive_send.c#L599-L608
5. you can see the issue is detected after sync to the latest libspdm,  in the `spdm-emu` PR [Update to latest libspdm](https://github.com/DMTF/spdm-emu/pull/264).
https://github.com/DMTF/spdm-emu/actions/runs/5283717519/jobs/9560316380?pr=264

> LIBSPDM_ASSERT: /home/runner/work/spdm-emu/spdm-emu/libspdm/library/spdm_responder_lib/libspdm_rsp_chunk_get.c(122): spdm_response->chunk_size < get_info->large_message_size

**Comment by Zhiqiang520** [comment]
BTW,  I think `spdm_context->connection_info.capability.data_transfer_size` should be change to `LIBSPDM_MIN(spdm_context->connection_info.capability.data_transfer_size, context->local_context.capability.sender_data_transfer_size)`
at the following line 107, 117 and 136 in the current latest `libspdm`.
https://github.com/DMTF/libspdm/blob/6674aa87c5a3b6991e25e22fcd1bf44e2a111331/library/spdm_responder_lib/libspdm_rsp_chunk_get.c#L105-L107
https://github.com/DMTF/libspdm/blob/6674aa87c5a3b6991e25e22fcd1bf44e2a111331/library/spdm_responder_lib/libspdm_rsp_chunk_get.c#L115-L119
https://github.com/DMTF/libspdm/blob/6674aa87c5a3b6991e25e22fcd1bf44e2a111331/library/spdm_responder_lib/libspdm_rsp_chunk_get.c#L135-L139

**Comment by jyao1** [comment]
> I think spdm_context->connection_info.capability.data_transfer_size should be change to LIBSPDM_MIN(spdm_context->connection_info.capability.data_transfer_size, context->local_context.capability.sender_data_transfer_size)

That seems a good idea.
I believe max_spdm_msg_size should also be changed to LIBSPDM_MIN(max_spdm_msg_size, sender_data_transfer_size).

**Comment by steven-bellock** [comment]
Thanks @Zhiqiang520. There's a lot wrong in `libspdm_build_response` with respect to chunking, so maybe I will rename this issue to "Fix Chunking". 😄 
```
    if ((status == LIBSPDM_STATUS_SUCCESS) &&
        (((context->connection_info.capability.data_transfer_size != 0) &&
          (my_response_size > context->connection_info.capability.data_transfer_size)) ||
         ((context->local_context.capability.sender_data_transfer_size != 0) &&
          (my_response_size > context->local_context.capability.sender_data_transfer_size))) &&
        libspdm_is_capabilities_flag_supported(
            context, false, 0,
            SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CHUNK_CAP)) {
        #if LIBSPDM_ENABLE_CAPABILITY_CHUNK_CAP
```

 1. `LargeResponse` and `ResponseTooLarge` can only be sent if the negotiated SPDM version is >= 1.2 There is no version check in `libspdm_build_response`. To catch this sooner, maybe `libspdm_generate_error_response` should have a bunch of assertions that check that the error code is appropriate for the negotiated version.
 2. The `#if LIBSPDM_ENABLE_CAPABILITY_CHUNK_CAP` should be before the runtime check, since if `SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CHUNK_CAP` is set then `LIBSPDM_ENABLE_CAPABILITY_CHUNK_CAP` must be true.
 3. In the event where the Requester does not support chunking but the message is larger than the transmit buffer size of the Responder, the Responder needs to send an error to the Requester. This can't be `ResponseTooLarge` since that is only for when the message is too large for the Requester, so we can use `Unspecified` until we get the specification clarified.

**Comment by jyao1** [comment]
> This can't be ResponseTooLarge.

The SPDM spec says: "The response is greater than the MaxSPDMmsgSize of the requesting SPDM endpoint."
Why it cannot be used?

**Comment by steven-bellock** [comment]
@jyao1 see https://github.com/DMTF/SPDM-WG/issues/2931.

**Comment by steven-bellock** [comment]
@steven-bellock to break out https://github.com/DMTF/libspdm/issues/2141#issuecomment-1594855129 into separate issues.
