### ISSUE TITLE
Unit tests use incorrect measurement summary hash macros

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2259]
For example https://github.com/DMTF/libspdm/blob/3f215681eb21bdb50141645720d10e259eced37e/unit_test/test_spdm_responder/key_exchange.c#L26-L28 `SPDM_CHALLENGE_REQUEST_NO_MEASUREMENT_SUMMARY_HASH` should be `SPDM_KEY_EXCHANGE_REQUEST_NO_MEASUREMENT_SUMMARY_HASH`. In addition there is no corresponding macro for `PSK_EXCHANGE`.

**Comment by Zhiqiang520** [comment]
I will take this.

**Comment by Zhiqiang520** [comment]
Not only the unit tests, but also the function codes use incorrect measurement summary hash macros. for example,
`SPDM_CHALLENGE_REQUEST_NO_MEASUREMENT_SUMMARY_HASH` at the following line 288:
https://github.com/DMTF/libspdm/blob/3f215681eb21bdb50141645720d10e259eced37e/library/spdm_responder_lib/libspdm_rsp_key_exchange.c#L287-L292
`SPDM_CHALLENGE_REQUEST_NO_MEASUREMENT_SUMMARY_HASH` at the following line 323:
https://github.com/DMTF/libspdm/blob/3f215681eb21bdb50141645720d10e259eced37e/library/spdm_responder_lib/libspdm_rsp_psk_exchange.c#L322-L328

**Comment by Zhiqiang520** [comment]
1. Go deep into review, `libspdm_get_measurement_summary_hash_size()` function was a **common** function called by `challenge` , `key_exchange` and `psk_exchange`.
https://github.com/DMTF/libspdm/blob/3f215681eb21bdb50141645720d10e259eced37e/library/spdm_responder_lib/libspdm_rsp_challenge_auth.c#L109-L110
https://github.com/DMTF/libspdm/blob/3f215681eb21bdb50141645720d10e259eced37e/library/spdm_responder_lib/libspdm_rsp_key_exchange.c#L284-L285
https://github.com/DMTF/libspdm/blob/3f215681eb21bdb50141645720d10e259eced37e/library/spdm_responder_lib/libspdm_rsp_psk_exchange.c#L197-L198
2. But `libspdm_get_measurement_summary_hash_size()` function does not distinguish `challenge` , `key_exchange` and `psk_exchange`, it always use `SPDM_CHALLENGE_REQUEST_NO_MEASUREMENT_SUMMARY_HASH`, `SPDM_CHALLENGE_REQUEST_TCB_COMPONENT_MEASUREMENT_HASH` and `SPDM_CHALLENGE_REQUEST_ALL_MEASUREMENTS_HASH`.
https://github.com/DMTF/libspdm/blob/3f215681eb21bdb50141645720d10e259eced37e/library/spdm_common_lib/libspdm_com_crypto_service.c#L1149-L1173
3. due to the above status, I prefer to **not distinguish** `challenge` , `key_exchange` and `psk_exchange`, just delete the current `SPDM CHALLENGE request HashType` and `SPDM KEY_EXCHANGE request HashType` and define **new common** measurement summary hash type, such as `REQUEST_NO_MEASUREMENT_SUMMARY_HASH`, `REQUEST_TCB_COMPONENT_MEASUREMENT_HASH` and `REQUEST_ALL_MEASUREMENTS_HASH`.
https://github.com/DMTF/libspdm/blob/3f215681eb21bdb50141645720d10e259eced37e/include/industry_standard/spdm.h#L495-L498
https://github.com/DMTF/libspdm/blob/3f215681eb21bdb50141645720d10e259eced37e/include/industry_standard/spdm.h#L733-L736

**Comment by steven-bellock** [comment]
Yeah it's fine to use a generic macro in libspdm. For completeness though I would say have the four macro groups in `spdm.h`.
- `SPDM_CHALLENGE_REQUEST_*`
- `SPDM_KEY_EXCHANGE_REQUEST_*`
- `SPDM_PSK_EXCHANGE_REQUEST_*`
- `SPDM_REQUEST_*`

And define the `SPDM_CHALLENGE_REQUEST_*` etc macros from the generic macros.

**Comment by Zhiqiang520** [comment]
Agree.
