### ISSUE TITLE
[SPDM 1.3] CHALLENGE: Add context field

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#2282]

**Comment by l1k** [comment]
The <a href="https://lore.kernel.org/all/cover.1695921656.git.lukas@wunner.de/">Linux kernel's SPDM requester</a> supports SPDM 1.3 and current master of libspdm claims that it supports SPDM 1.3 as well, but the missing `RequesterContext` field in CHALLENGE_AUTH responses means that the kernel will reject the response:

```
[   10.475246] nvme 0000:00:03.0: SPDM: Truncated challenge_auth response
```

So libspdm's current master is broken when used against the Linux kernel. libspdm should not select version 1.3 if it doesn't actually support it.

This issue was reported by @tsarvela. Heads up @twilfredo @alistair23 !

**Comment by twilfredo** [comment]
> The [Linux kernel's SPDM requester](https://lore.kernel.org/all/cover.1695921656.git.lukas@wunner.de/) supports SPDM 1.3 and current master of libspdm claims that it supports SPDM 1.3 as well, but the missing `RequesterContext` field in CHALLENGE_AUTH responses means that the kernel will reject the response:
> 
> ```
> [   10.475246] nvme 0000:00:03.0: SPDM: Truncated challenge_auth response
> ```
> 
> So libspdm's current master is broken when used against the Linux kernel. libspdm should not select version 1.3 if it doesn't actually support it.
> 
> This issue was reported by @tsarvela. Heads up @twilfredo @alistair23 !

I had a quick go at trying to reproduce this today. But it seemed to work... I was testing on QEMU with libspdm@2565e47321 based responder and kernel on linux@b6c714ff335e (latest on doe branch). 

With the usual process of adding the certificates to the key-ring then authenticating.

```
nvme 0000:00:03.0: CMA: authenticated with certificate slot 0
```
Was this addressed or did I miss something? Looks like the issue is still open too...

**Comment by l1k** [comment]
@twilfredo Hm, perhaps you've specified `--ver 1.2` on the `spdm_responder_emu` command line? I can still reproduce the issue with f029916052f1. Reverting ea5c9246ed4e avoids the issue. But I see @jyao1 is on it. Thanks for testing!

**Comment by twilfredo** [comment]
> @twilfredo Hm, perhaps you've specified `--ver 1.2` on the `spdm_responder_emu` command line? I can still reproduce the issue with [f029916](https://github.com/DMTF/libspdm/commit/f029916052f1750591bd52e4f7a97cf2fab8f7b3). Reverting [ea5c924](https://github.com/DMTF/libspdm/commit/ea5c9246ed4e1752057708de7aaadcaf89fdb3ee) avoids the issue. But I see @jyao1 is on it. Thanks for looking into it!

Indeed I was using the wrong version in our test-tool, thanks for that! I can re-produce this on my end also on 1.3.
