### ISSUE TITLE
remove dynamic function pointer registration

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#259]
Per @steven-bellock, always request to link function statically. Here is list of function pointers.

Do we want to create static libraries for those APIs?

1. IO, function
```
	//
	// IO information
	//
	spdm_device_send_message_func send_message;
	spdm_device_receive_message_func receive_message;
```

2. Transport layer function
```
	//
	// Transport Layer infomration
	//
	spdm_transport_encode_message_func transport_encode_message;
	spdm_transport_decode_message_func transport_decode_message;
```

3. vendor defined opcode response function
```
	//
	// Register GetResponse function (responder only)
	//
	uintn get_response_func;
	//
	// Register GetEncapResponse function (requester only)
	//
	uintn get_encap_response_func;
```

4. connection or session_state callback function
```
	//
	// Register spdm_session_state_callback function (responder only)
	// Register can know the state after StartSession / EndSession.
	//
	uintn spdm_session_state_callback[MAX_SPDM_SESSION_STATE_CALLBACK_NUM];
	//
	// Register spdm_connection_state_callback function (responder only)
	// Register can know the connection state such as negotiated.
	//
	uintn spdm_connection_state_callback
		[MAX_SPDM_CONNECTION_STATE_CALLBACK_NUM];
```

5. verify cert callback function
```
	// Peer Cert verify
	spdm_verify_spdm_cert_chain_func verify_peer_spdm_cert_chain;
```

**Comment by markusfnx** [comment]
Even though function pointers are appreciated for their flexibility, I also see a potential security risk of passing an arbitrary point in memory (rather than a valid function) as pointer. 

One suggestion to address this issue is to have a fixed function_x that acts as a “translator”: it is always the function to be called when a pointer would be inserted, and internally it calls the function that would be the target of a pointer. For example, if there are two expected function pointers, for functions foo() and bar(), then we would have something like:

```
return_value  function_x(){
      switch (VARIABLE_THAT_CONTROLS_FUNCTION_POINTERS){
             case CALL_FOO: 
                    return foo();
            case CALL_BAR:
                    return bar();
     }
     return “Invalid call”; //limits the scope to acceptable functions 
}
```
     
This approach preserves the flexibility of function pointers, since new cases can be added as needed, while limiting the calls to those specific functions (thus avoiding misuse).

**Comment by steven-bellock** [comment]
Deferred as high priority to next stable release.

**Comment by jyao1** [comment]
Discussed in Feb 1, 2022. Not target for next stable release.

**Comment by richkong88** [comment]
Following. My team has interest in removing these as well.

**Comment by jyao1** [comment]
Concern: the vulnerability may allow attacker to modify the function pointer, if the function pointer is treated as modifiable data.

The direct call is not a problem, because the attacker cannot modify the function address in RO code memory, if it is protected.
The indirect call may be a problem, because the function address is stored in RW data memory or register.

**Comment by steven-bellock** [comment]
The function pointer registration examples above are fine in my opinion. However there are places in the library, most notably `spdm_crypt_lib` where function pointers exist when they don't need to. I'll close this issue and open a new issue for those cases.
