### ISSUE TITLE
Add a check for DHE key generation to see if public keys from both endpoint is same

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#2639]
If they are same, key need to be regenerated.

Although the probability is very very low.

This is feedback from SPDM WG.

**Comment by mcsmonk** [comment]
I agree the conclusion https://github.com/DMTF/SPDM-WG/issues/3431#issuecomment-2022821742, which such vurnerability should be issued in whitepaper

I'm wondering why/how the conclusion should be added in library.

The probability is extremely unlikely, and there are some cumbersome cases, which device cannot regenerate key pair and its corresponding leaf cert.
For example, device model device cannot regenerate leaf cert itself. Alias model device need to be reboot in order to regenerate certificate chain.

**Comment by steven-bellock** [comment]
The SPDM Working Group has not demonstrated that this is a security issue. We can hold off on this until it is demonstrated.

**Comment by steven-bellock** [comment]
After discussion in the SPDM Working Group, the security is weakened only if the Requester does not authenticate the Responder. Will close this issue since SPDM effectively requires authentication during key exchange.
