### ISSUE TITLE
Allow Integrator to ignore unsupported critical extensions

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#2678]
By default any unhandled critical extensions in certificates or (if checked) CRLs result in a fatal error.
But the actual cert may have the customized critical extension. 
It is better to add the flag to ignore unhandled critical extensions when the user want to ignore.

https://github.com/DMTF/libspdm/blob/ab6e3436413e23cd2339e7d053a91c7b0ae423ae/os_stub/openssllib/openssl_gen/openssl/x509_vfy.h#L425-L426

**Comment by steven-bellock** [comment]
From [RFC 5280:](https://www.rfc-editor.org/rfc/rfc5280#section-4.2)
>The X.509 v3 certificate format also allows communities to define private extensions to carry information unique to those communities.  Each extension in a certificate is designated as either critical or non-critical.  A certificate-using system MUST reject the certificate if it encounters a critical extension it does not recognize or a critical extension that contains information that it cannot process.  A non-critical extension MAY be ignored if it is not recognized, but MUST be processed if it is recognized.

From [OpenSSL](https://www.openssl.org/docs/man3.0/man1/openssl-verification-options.html):
>Normally if an unhandled critical extension is present that is not supported by OpenSSL the certificate is rejected (as required by RFC5280).

So for the cryptography libraries that libspdm supports, I think it's fine if this check is on by default, and that it can be disabled explicitly. Note that, while this issue is currently for OpenSSL, presumably the same disablement also applies to MbedTLS. I'll rename the issue.

https://github.com/DMTF/libspdm/blob/ab6e3436413e23cd2339e7d053a91c7b0ae423ae/os_stub/mbedtlslib/include/mbedtls/config.h#L2206-L2213
