### ISSUE TITLE
need a way to pass non-zero timeout value to spdm IO.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#272]
Current libspdm always uses 0, which means infinite wait for response.

**Comment by jcahill0** [comment]
Few ideas:

1. Change the API for every command to add a timeout parameter
  a. Brute force and puts a lot of work on the client of the lib
2. Add a per-SPDM context parameter to set the SPDM RTT
  b. libspdm can then more elegantly pass down RTT, and if a crypt-calc is involved, add CT Exponent as appropriate
3. Nuance the timeout parameter to the transport callbacks to do the work of using the right timeout.  This is appropriate in one way as it is much like how RTT and timeouts are defined and layered in the specs, but also inappropriate because it still puts a ton of work on the client that is less elegant than 2 above.  Transport would need to handle
   a. No timeout
   b. RTT timeout
   c. RTT + CT Exponent timeout
   d. Custom timeout
4. A hybrid of 1 and 2 above.  Certain calls should 1 above with RTT and RTT+CT Exponent, e.g. GET_VERSION and CHALLENGE.  Others should use 2 above for a Secure Msg Request that goes out and waits for a Secure Msg Response.

**Comment by jcahill0** [comment]
One other level of decision is whether libspdm will bake in each transport's RTT or the client will do this.  I'm for the client doing it as new transports can come up without SPDM being directly involved: SPDM over MCTP over <X> binding, where <X> is a new binding to MCTP and has a unique MT1 and MT2.

**Comment by jyao1** [comment]
@jcahill0, please let me know if you want to lead the discussion? I would like to assign the owner to you, if you are OK with that.

**Comment by jyao1** [comment]
11/15/2021 - For SPDM message, let user set in the context once.
For SPDM vendor-defined / secure application message, let user input every time.

**Comment by jyao1** [comment]
Also need consider how to add unit test for the timer.

**Comment by qizhangz** [comment]
I will check it

**Comment by qizhangz** [comment]
I made PR to add timeout for SPDM message. Could you please review if it is what you want? Thank you!

https://github.com/DMTF/libspdm/pull/309

**Comment by steven-bellock** [comment]
Will defer to STABLE 0.2.
