### ISSUE TITLE
the vendor_cmds requester unit_test has some error

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#2780]
When any requester unit_test is called after the vendor_cmds requester unit_test, the GCC release build failed.

There is a example PR:
https://github.com/Wenxing-hou/libspdm/pull/17

**Comment by steven-bellock** [comment]
Removing `-flto` from compilation will let this pass. Seems to be a compiler bug. Tested on 
>gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

**Comment by steven-bellock** [comment]
Also reproduces in
> gcc-14 (Ubuntu 14-20240412-0ubuntu1) 14.0.1 20240412 (experimental) [master r14-9935-g67e1433a94f]

**Comment by steven-bellock** [comment]
This is "fixed" by moving https://github.com/DMTF/libspdm/blob/a3e5b9966da2021a5908420a5bfa51634eebc1e5/unit_test/test_spdm_requester/vendor_request.c#L222-L227 and https://github.com/DMTF/libspdm/blob/a3e5b9966da2021a5908420a5bfa51634eebc1e5/unit_test/test_spdm_requester/error_test/vendor_request_err.c#L219-L224 inside their respective `_main` functions. This should be done anyways since those values are not needed at file scope and definitely do not need external linkage.

**Comment by steven-bellock** [comment]
https://github.com/DMTF/libspdm/blob/704d5652b2eeb451fffbd1bb1129046e377c9cf3/unit_test/test_spdm_requester/vendor_request.c#L130-L131 https://github.com/DMTF/libspdm/blob/704d5652b2eeb451fffbd1bb1129046e377c9cf3/unit_test/test_spdm_requester/error_test/vendor_request_err.c#L118-L119

Also use of `spdm_test_context` is incorrect. It should be `spdm_context`. I'm surprised the call to the function is successful, but that's C for you. This issue was found by Rani at NVIDIA using his formal verification tool.
