### ISSUE TITLE
Build error with Openssl for ia32 in Linux

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#280]
When build in Linux for ia32, build error take place.
The reproduce step is:

- cmake -DARCH=ia32 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=openssl ..     (the error is same in debug and release )
- make copy_sample_key
- make

the error is:
_In file included from /home/houwenxi/libspdm/library/spdm_requester_lib/libspdm_req_get_capabilities.c:8:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
   27 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated._

**Comment by jyao1** [comment]
@steven-bellock , is that related to your update?

**Comment by steven-bellock** [comment]
I just renamed files, so probably not. 
@Wenxing-hou in the past were you able to successfully compile -DARCH=ia32 on a 64-bit machine? Or is this your first attempt?

**Comment by jyao1** [comment]
OK. I think it is caused by stdio.h,  https://github.com/DMTF/libspdm/issues/98

**Comment by steven-bellock** [comment]
Yes, stdio.h shouldn't be in that file, but there are other issues as well.

@Wenxing-hou when building a 32-bit application on a 64-bit system you sometimes need to install the 32-bit headers and runtimes. See, for example https://askubuntu.com/questions/1270351/how-to-compile-32-bit-executable-on-64-bit-system

@jyao1 when I tried to compile I got `Architecture of i386 input file is incompatible with i386:x86-64` during linking. This is because the linker is expecting a 64-bit ELF file and instead got, correctly, a 32-bit ELF file. I added 
```
    elseif(ARCH STREQUAL "ia32")
        SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m32")
        **SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -m32" )**
    endif()
```
and that fixes things.

**Comment by jyao1** [comment]
thank you! Looks good.

I feel bad that 32bit is not tested for a while. Any chance to add to CI?

**Comment by steven-bellock** [comment]
We can do that after the freeze, although we need to make sure the build works on a real 32-bit OS and machine.

**Comment by jyao1** [comment]
agree

**Comment by steven-bellock** [comment]
According to https://github.com/actions/runner/issues/1181 looks like we'll need QEMU to test it out on 32-bit Linux.

**Comment by jyao1** [comment]
11/15/21 - approved.
We should update readme to add those information.
