### ISSUE TITLE
Is there a script that uses openssl to verify the certificates in the certificate chain or some tool?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2826]

**Comment by steven-bellock** [comment]
[openssl verify](https://docs.openssl.org/1.1.1/man1/verify/) will verify / validate a certificate chain. I have also thought that https://github.com/DMTF/SPDM-Responder-Validator should have a standalone SPDM certificate chain validation tool, so that folks can validate their certificate chains to the SPDM specification without having to construct a full Responder.

**Comment by PrakashK94** [comment]
Any other tool available?
Have you ever verified it using openssl verify tool? Can you share an example?

**Comment by steven-bellock** [comment]
> Any other tool available?

Probably? Most folks use OpenSSL because it's free and comes pre-installed on a lot of Linux distributions.

> Can you share an example?
```
libspdm/unit_test/sample_key/rsa2048>cat ca.cert inter.cert end_responder.cert > chain.cert
libspdm/unit_test/sample_key/rsa2048>openssl verify -CAfile ca.cert chain.cert
chain.cert: OK

**Comment by steven-bellock** [comment]
@PrakashK94 if this answered your question please close the issue.
