### ISSUE TITLE
First GET_CERTIFICATE.offset needs to be checked

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#312]
In the 1.1 specification GET_CERTIFICATE.offset contains the text
> For the first GET_CERTIFICATE request, the Requester shall set this field to 0.

The libspdm Responder does not check that the first GET_CERTIFICATE request is 0. I've filed https://github.com/DMTF/Security-TF/issues/1673 to figure out what "first" means.

**Comment by jyao1** [comment]
The problem is how the responder decides if a request message is "first" ?

For example, for a 2048 length certificate, if a requester sends:
GET_CERTIFICAT (offset 0, len 512)
GET_CERTIFICAT (offset 512, len 512)
<----- for some reason, request resends from the beginning, because some error in transport layer.
GET_CERTIFICAT (offset 0, len 512)
GET_CERTIFICAT (offset 512, len 512)
GET_CERTIFICAT (offset 1024, len 512)
GET_CERTIFICAT (offset 1536, len 512)

Is that valid sequence ?

**Comment by rw8896** [comment]
IMO, this is more like a guideline for the requester to follow because the Requester must "first" read the Length field at offset 0 to get the total length for the Certificate chain.

As @jyao1 mentioned, it's hard to define "first" for the responder to validate.

**Comment by jyao1** [comment]
11/29/2021 - wait for the response from security TF.

**Comment by steven-bellock** [comment]
According to https://github.com/DMTF/Security-TF/issues/1673 the Security TF said the Responder shouldn't be checking that.
