### ISSUE TITLE
Why does the library define its own fixed-width integer types, instead of using <stdint.h>?

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#62]
And if we can't think of a good reason, then let's use types from <stdint.h>.

**Comment by ayj** [comment]
<stdint.h> was introduced in C99. I don't see any mention of C89 vs. C99 in libspdm, however, if libspdm targets C89 support, it would still be nice to aim for compatibility with C99/C++ when possible, e.g. define fixed-width integer types in C99 style, avoid use of reserved keywords (e.g. `public`).

**Comment by steven-bellock** [comment]
Since all the for loops are of the form

> for (index = 0; index < size; index++)

instead of the more natural

> for (int index = 0; index < size; index++)

it seems like it implicitly targets C89. I can add that topic to the next meeting: "What C standard should libspdm target?"

**Comment by jyao1** [comment]
The target is libspdm to build with MSVC/GCC/LLVM.

It is hard to say C99, because not all compilers support all features in C99.

A typical example is variable length array (VLA). It is defined in C99, but not supported by MSVC. So we cannot claim C99 support.

**Comment by ayj** [comment]
Which version(s) of MSVC/GCC/LLVM are targeted? For example, newer MSVC versions seem to support C11 (https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc), though presumably older toolchains may still matter?

Supported least common denominator seems reasonable for a low-level common library (i.e. C89). Some extra care to avoid conflicts with newer toolchains (C++) would also be helpful, e.g. don't name variables `public`.

**Comment by jyao1** [comment]
The target compiler is defined in https://github.com/DMTF/libspdm/blob/main/CMakeLists.txt.
For MSVC, we support VS2015, VS2019, so far.

To support old compiler does matter, because libspdm is NOT a standalone project. It may be submoduled into other project.
We cannot assume all other libspdm consumers are using latest compilers.

I think the key to list how many compilers we support, instead of C89, C99, C11 - which is too high level.

I don't object the idea to change, as long as we still support those compilers.
I really hope we can setup CI to test the  compiler compatibility for every patch.

**Comment by steven-bellock** [comment]
If we allow C99 constructs then we can restrict what is allowed. For example the Linux kernel purged all use of VLAs. I just want to use <stdint.h> and not have to declare for-loop indices outside of the for-loop.

**Comment by steven-bellock** [comment]
Maybe we can use stdint.h and the corresponding fixed-width types. Need to ensure, through CI, that all the architectures are supported.

**Comment by steven-bellock** [comment]
libspdm now includes stdint.h by default, but library client can override it if they desire.
