### ISSUE TITLE
libspdm_rsp_psk_exchange not processing psk_hint field

### ISSUE THREAD

**Issue by ecominetti** [DMTF/libspdm#886]
I am creating some additional tests for psk_exchange messages and notice that the responder does not process the psk_hint field (which is optional) in libspdm_rsp_psk_exchange.c

Example:

In the unit_test/test_spdm_responder/psk_exchange.c, the psk_hint field is created on lines 94-96 and it is stored on the appropriate fields of spdm_context on lines 97-99.
Then, the request message also receives the value (lines 101-102 and 110-113).
However, the psk_hint field from the request message is not processed in the libspdm_rsp_psk_exchange.c, where it uses the value already set in the local_context (the value is used inside the libspdm_generate_session_handshake_key, line 299).
Because the value in the unit_test message is copied from the one stored on the spdm_context, no error is detected.

Suggested fix:

Before libspdm_generate_session_handshake_key is called in libspdm_rsp_psk_exchange.c, check the psk_hint size. If 0, set psk_hint to null. Else, set spdm_context->local_context.psk_hint and  spdm_context->local_context.psk_hint_size to the ones received in the request message.

**Comment by steven-bellock** [comment]
Shouldn't it be in `session_info->secured_message_context`? That's what gets passed to `libspdm_generate_session_handshake_key`.

**Comment by qizhangz** [comment]
> Shouldn't it be in `session_info->secured_message_context`? That's what gets passed to `libspdm_generate_session_handshake_key`.

it will be passed from spdm_context->local_context to session_info->secured_message_context in the below flow.
libspdm_assign_session_id() -> libspdm_session_info_init() -> libspdm_secured_message_set_psk_hint()

**Comment by steven-bellock** [comment]
Ah thanks. But the use of the Responder's `local_context` to store the Requester's fields is strange, since the Responder's `local_context` is for long-standing parameters that won't change and are independent of the Requester. The way it's being used in the PR is a temporary storage location before being stored into `session_info`. It should probably in `connection_info` or passed as parameters to `libspdm_assign_session_id`.

**Comment by steven-bellock** [comment]
Ah thanks. But the use of the Responder's `local_context` to store the Requester's fields is strange, since the Responder's `local_context` is for long-standing parameters that won't change and are independent of the Requester. The way it's being used in the PR is a temporary storage location before being stored into `session_info`. It should probably in `connection_info` or passed as parameters to `libspdm_assign_session_id`.
